name: NBTUtility
version: '${version}'
main: net.azisaba.nbtutility.NBTUtility
api-version: '1.15'
authors: [Azisaba Network]
commands:
  nbt:
    description: NBT utility command.
    usage: /nbt <sync|add|remove|compare|view>
    permission: nbtutility.admin

permissions:
  nbtutility.admin:
    description: Allows the user to use the NBT utility commands.
    default: op